version: '2.0'
services:

  cassandra:
    image: cassandra:3.11.8
    container_name: cassandra
    ports:
    - "9042:9042"
    volumes:
    - ./scripts:/scripts
    - ./data/cassandra:/data
    - ./cassandra-data:/var/lib/cassandra  
 
  mysql:
    image: mysql:8.0.16    
    container_name: mysql
    hostname: mysql
    ports:
        - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 500m    
    volumes:        
        - ./scripts/mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
        MYSQL_ROOT_USER: mama
        MYSQL_ROOT_PASSWORD: mama
        MYSQL_DATABASE: mydatabase
        MYSQL_USER: mama
        MYSQL_PASSWORD: mama
  
  jupyter:
    image: jupyter/all-spark-notebook:latest
    container_name: jupyter
    ports:
    - "8888:8888/tcp"
    - "4040:4040/tcp"
    working_dir: /home/$USER/work
    environment:
      CHOWN_HOME: "yes"
      GRANT_SUDO: "yes"
      NB_UID: 1000
      NB_GID: 100
      NB_USER: $USER
      NB_GROUP: staff
    user: root
    deploy:
     replicas: 1
     restart_policy:
       condition: on-failure
    volumes:
      - ./data/jupyter/work:/home/$USER/work
      - ./data/cassandra:/home/$USER/data
      - ./data/jupyter/libs:/home/$USER/libs

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
    - "8080:8080/tcp"    
    deploy:
     restart_policy:
       condition: on-failure

       