AWSTemplateFormatVersion: '2010-09-09'
Description: Bucket of Lambdas and Data
Resources:
  LambdaBuckets:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: lambdas-ortiz-2020
  DataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: data-ortiz-2020
  LambdaBucketArn:
        Type: AWS::SSM::Parameter        
        Properties:
            Name: LambdaBucketsARN
            Type: String
            Value: !Sub '${LambdaBuckets.Arn}'
  DataBucketArn:
        Type: AWS::SSM::Parameter        
        Properties:
            Name: DataBucketARN
            Type: String
            Value: !Sub '${DataBucket.Arn}'